services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  app:
    build: .
    image: app
    container_name: app-container
    ports:
      - 8080:80