"""add transaction amount index

Revision ID: 274b1c30e547
Revises: fccb724f68df
Create Date: 2023-12-03 23:47:38.606694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274b1c30e547'
down_revision: Union[str, None] = 'fccb724f68df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transaction_amount'), 'transaction', ['amount'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_amount'), table_name='transaction')
    # ### end Alembic commands ###
