"""drop transaction amount index

Revision ID: fccb724f68df
Revises: 46968bec4e58
Create Date: 2023-12-03 23:45:27.627600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fccb724f68df'
down_revision: Union[str, None] = '46968bec4e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_amount', table_name='transaction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transaction_amount', 'transaction', ['amount'], unique=False)
    # ### end Alembic commands ###
